python sample.py \
    --ckpt_dir="ckpt/" \
    --style_image_path="data_examples/sampling/example_style.png" \
    --character_input \
    --content_character="隆" \
    --save_image \
    --save_image_dir="outputs/" \
    --device="cuda:0" \
    --algorithm_type="dpmsolver++" \
    --guidance_type="classifier-free" \
    --guidance_scale=7.5 \
    --num_inference_steps=20 \
    --method="multistep" \
    --ttf_path='ttf/SourceHanSerifTC-VF.ttf'